[package]
name = "pdf-crypto"
version = "0.1.0"
edition = "2021"
description = "A comprehensive PDF encryption/decryption library for Rust"
authors = ["kartik6717"]
license = "MIT"
repository = "https://github.com/kartik6717/CloneX"
documentation = "https://docs.rs/pdf-crypto"
readme = "README.md"

[dependencies]
# Core cryptographic dependencies
aes = "0.8"           # AES encryption
des = "0.8"           # DES encryption (legacy PDFs)
rc4 = "0.8"           # RC4 encryption (PDF 1.4-1.6)
md5 = "0.8"           # MD5 hashing
sha1 = "0.10"         # SHA-1 hashing
sha2 = "0.10"         # SHA-256/384/512
rsa = "0.9"           # Public key encryption
x509-parser = "0.15"  # Certificate parsing

# Utility dependencies
num-bigint = "0.4"    # Large number operations
rand = "0.8"          # Random number generation
zeroize = "1.7"       # Secure memory clearing
thiserror = "1.0"     # Error handling
generic-array = "0.14" # Fixed-size arrays
block-modes = "0.9"   # Block cipher modes
cipher = "0.4"        # Crypto traits

# Additional required dependencies
byteorder = "1.4"     # Byte order handling
log = "0.4"           # Logging support
base64 = "0.13"       # Base64 encoding/decoding
hex = "0.4"           # Hex encoding/decoding

[dev-dependencies]
hex = "0.4"           # For test vectors
criterion = "0.4"     # For benchmarking
tempfile = "3.3"      # For temporary test files
rstest = "0.12"       # For parameterized testing
pretty_assertions = "1.3" # For better test output

[[bench]]
name = "crypto_benchmarks"
harness = false

[features]
default = ["std"]
std = []
legacy = ["des"]      # Enable legacy PDF encryption support
fips = []            # FIPS 140-2 compliant mode

[package.metadata]
msrv = "1.65.0"      # Minimum supported Rust version
