[package]
name = "pdf-crypto"
version = "0.1.0"
edition = "2021"
authors = ["kartik6717"]
description = "Complete PDF encryption/decryption library with all filters"
license = "MIT"
repository = "https://github.com/kartik6717/pdf-crypto"
documentation = "https://docs.rs/pdf-crypto"
keywords = ["pdf", "encryption", "security", "cryptography", "filters"]
categories = ["cryptography", "encoding", "compression"]

[dependencies]
# Cryptography
aes = "0.8.3"
des = "0.8.1"
rc4 = "0.8.1"
rsa = "0.9.3"
sha1 = "0.10.6"
sha2 = "0.10.8"
md5 = "0.8.0"
rand = "0.8.5"
base64 = "0.21.5"
zeroize = { version = "1.7.0", features = ["zeroize_derive"] }

# Compression and filters
flate2 = "1.0.28"
lzw = "0.10.0"
jpeg-decoder = "0.3.0"
jpeg-encoder = "0.5.1"
jbig2dec = "0.3.0"
ccitt = "0.2.2"
deflate = "1.0.0"

# Image processing
image = { version = "0.24.7", features = ["jpeg", "png"] }

# Utilities
thiserror = "1.0.49"
log = "0.4.20"
env_logger = "0.10.0"
byteorder = "1.5.0"
num-bigint = "0.4.4"
generic-array = "0.14.7"
hex = "0.4.3"

[dev-dependencies]
criterion = "0.5.1"
tempfile = "3.8.0"
rstest = "0.18.2"
pretty_assertions = "1.4.0"
test-log = "0.2.13"

[[bench]]
name = "crypto_benchmarks"
harness = false

[features]
default = ["all-filters"]
all-filters = []
minimal = []
fips = ["aes-gcm"]
