[package]
name = "pdf-crypto"
version = "0.1.0"
edition = "2021"
authors = ["kartik6717"]
description = "A comprehensive PDF encryption/decryption library for Rust"
license = "MIT"
repository = "https://github.com/kartik6717/pdf-crypto"
documentation = "https://docs.rs/pdf-crypto"
keywords = ["pdf", "encryption", "security", "cryptography"]
categories = ["cryptography", "encoding"]

[dependencies]
aes = "0.8.3"
des = "0.8.1"
rc4 = "0.8.1"
md5 = "0.8.0"
sha1 = "0.10.6"
sha2 = "0.10.8"
rsa = "0.9.3"
x509-parser = "0.15.1"
num-bigint = "0.4.4"
rand = "0.8.5"
zeroize = { version = "1.7.0", features = ["zeroize_derive"] }
thiserror = "1.0.49"
generic-array = "0.14.7"
block-modes = "0.9.1"
cipher = "0.4.4"
base64 = "0.21.5"
hex = "0.4.3"
log = "0.4.20"
byteorder = "1.5.0"

[dev-dependencies]
criterion = "0.5.1"
tempfile = "3.8.0"
rstest = "0.18.2"
pretty_assertions = "1.4.0"
env_logger = "0.10.0"
test-log = "0.2.13"

[[bench]]
name = "crypto_benchmarks"
harness = false

[features]
default = ["std", "aes-256"]
std = []
aes-256 = []
legacy = ["des"]
fips = []

[package.metadata]
msrv = "1.65.0"
